### ISSUE TITLE
Describe contribution and review process 

### ISSUE THREAD

**Issue by kyyberi** [APIOps/APIOps-cycles#2]
We need clear description of the process how to contribute and what happens to the contributions.

**Comment by kyyberi** [comment]
Here's one way to do it. Might be a bit heavy https://github.com/OAI/OpenAPI-Specification/blob/master/DEVELOPMENT.md

**Comment by kyyberi** [comment]
Proposal https://github.com/APIOps/APIOps-cycles/blob/master/DEVELOPMENT.md

**Comment by kyyberi** [comment]
This has been open for 22 days without any comments. I will close the issue and by so approve the proposed guideline for development. If there's opposing views to this, just raise an issue.

**Comment by mniinio** [comment]
Document was fine, I'm only thinking if there should be 
- specific dates agreed when and who will review the incoming changes (for example every 2 weeks) because it the same person makes the change and commits it, it's not good, sometimes you need to actually discuss the changes and also we need to have a  little bit of schedule since there is so many things going on at the moment in the API world. **I  suggest every other Friday starting from Nov 10th, 2017.** This should then also be our release cycle for minor changes. I'm also now inviting more of our team at Digia as members of this repo as I've now been the only one.
